import { Loader2 } from 'lucide-react';
import { cn } from 'shared/lib/utils';

interface LoadingSpinnerProps {
  size?: 'sm' | 'md' | 'lg';
  className?: string;
  text?: string;
}

/**
 * Standard Loading Spinner Component
 * 
 * @description Consistent loading indicator across the app
 * @author Generated by template
 */
export function LoadingSpinner({ 
  size = 'md', 
  className, 
  text = 'Đang tải...' 
}: LoadingSpinnerProps) {
  const sizeClasses = {
    sm: 'h-4 w-4',
    md: 'h-6 w-6', 
    lg: 'h-8 w-8'
  };

  return (
    <div className={cn(
      'flex flex-col items-center justify-center gap-2 p-4',
      className
    )}>
      <Loader2 className={cn(
        'animate-spin text-primary',
        sizeClasses[size]
      )} />
      {text && (
        <p className="text-sm text-muted-foreground">{text}</p>
      )}
    </div>
  );
}

/**
 * Full Page Loading Spinner
 * 
 * @description Loading spinner that covers the entire page
 */
export function PageLoadingSpinner({ text = 'Đang tải trang...' }: { text?: string }) {
  return (
    <div className="fixed inset-0 flex items-center justify-center bg-background/80 backdrop-blur-sm z-50">
      <LoadingSpinner size="lg" text={text} />
    </div>
  );
}

/**
 * Inline Loading Spinner
 * 
 * @description Small loading spinner for inline usage
 */
export function InlineLoadingSpinner({ className }: { className?: string }) {
  return (
    <Loader2 className={cn('h-4 w-4 animate-spin', className)} />
  );
}

export default LoadingSpinner; 
